CREATE TABLE TB_USER(
    ID VARCHAR(100) NOT NULL COMMENT '이메일 형식의 아이디',
    PWD VARCHAR(250) NOT NULL COMMENT '비밀번호',
    
    CONSTRAINT PK_ID PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_ARTICLE(
    SEQ BIGINT NOT NULL AUTO_INCREMENT,
    BBS_GROUP_ID VARCHAR(30) NULL COMMENT '게임 그룹 아이디',
    BBS_ID VARCHAR(30) NULL COMMENT '게임 게시판 아이디',
    GAME_NAME VARCHAR(40) NULL COMMENT '게임 이름', 
    ARTICLE_ID BIGINT NULL COMMENT '게시글 고유 아이디',
    WRITER VARCHAR(40) NULL COMMENT '게시글 작성자',
    TITLE VARCHAR(200) NULL COMMENT '제목',
    CONTENT MEDIUMTEXT NULL COMMENT '게시글 내용 ',
    REG_DATE DATE NULL COMMENT '게시글 작성일',
    LIKE_CNT BIGINT NULL COMMENT '좋아요 수',
    UNLIKE_CNT BIGINT NULL COMMENT '싫어요 수',
    COMMENT_CNT BIGINT NULL COMMENT '댓글 수',
    VIEW_CNT BIGINT NULL COMMENT '조회 수',

    CONSTRAINT PK_ARTICLE_SEQ PRIMARY KEY (SEQ),
    CONSTRAINT UNQ_ARTICLE_SEQ UNIQUE KEY (ARTICLE_ID),
    INDEX IDX_REG_DATE (REG_DATE DESC)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_GAME(
    SEQ BIGINT NOT NULL AUTO_INCREMENT,
    GAME_NAME VARCHAR(40) NOT NULL COMMENT '게임 제목',
    TARGET_URL VARCHAR(100) NOT NULL COMMENT '크롤링 대상 URL',
    
    CONSTRAINT PK_CRAWLING_SEQ PRIMARY KEY (SEQ)
) DEFAULT CHARSET=utf8;

INSERT INTO TB_GAME
  (GAME_NAME, TARGET_URL)
  VALUES
  ('DRAGONFLIGHT', 'https://square.line.games/dragonflight?lang=ko'),
  ('ELBRISA', 'https://square.line.games/elbrisa?lang=ko'),
  ('SPRITCATCHER', 'https://square.line.games/spiritcatcher?lang=ko');

/* 임 시 pwd : 12377777774 */
INSERT INTO TB_USER
  (ID, PWD)
  VALUES
  ('severalday@naver.com', '0782b380ef7559a8af44e6536680f3b4546e2fad02fdfdf9e71797bdfe3cc359');